name: Draft release for plugin to GitHub

on:
  push:
    tags:
      - "v*"
jobs:
  draft_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get version from tag
        id: tag_name
        run: echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.1.1
        with:
          validation_level: warn
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build Plugin
        env:
          VERSION: ${{ steps.changelog_reader.outputs.version }}
          CHANGE_NOTES: ${{ steps.changelog_reader.outputs.changes }}
        run: ./gradlew buildPlugin
      - name: Get distribution
        run: cp build/distributions/*.zip .
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.zip"
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: true




